name: "sbc2ha"
description: "Single board computer 2 home assistant"
version: "0.0.7-2"
slug: "sbc2ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/dafik/Hassio-Addons/tree/main/sbc2ha-test
image: docker.io/sbc2ha/sbc2ha-ha-addon
hassio_api: true
hassio_role: default
ingress: true
ingress_port: 8080
options:
  pigpio_host: null
schema:
  pigpio_host: str

